# Generated by Django 5.0 on 2023-12-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='team',
            field=models.IntegerField(default=1, verbose_name='team number'),
        ),
    ]
