# Generated by Django 5.0 on 2023-12-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_rename_blog_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('authenticated', 'Authenticated'), ('team', 'Team'), ('owner', 'Owner')], default='public', max_length=15),
        ),
    ]
